sudo: false
language: python
# This only controls the version of Python used to run tox,
# the versions used for the tests are handled by tox itself.
python: "2.7"
env:
    - TOX_ENV=docs
    - TOX_ENV=py27-django1.6-drf3.2
    - TOX_ENV=py27-django1.7-drf3.2
    - TOX_ENV=py27-django1.8-drf3.2
    - TOX_ENV=py34-django1.8-drf3.2
matrix:
    fast_finish: true
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
