language: python
python:
    - "2.7"
    - "3.3"
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=docs
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
notifications:
  irc:
    channels:
      - "irc.mozilla.org#payments"
    on_success: change
    on_failure: always
